[workspace]
resolver = "2"
members = [
    "bin/the-collector",
    "bin/bot",
    "lib/the-collector-db",
    "lib/the-collector-ipc",
    "lib/the-collector-evaluation",
]

[workspace.package]
version = "0.1.0"
