// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use crate::db::schema::*;
use diesel::prelude::*;
use serde::{Deserialize, Serialize};

use chrono::NaiveDateTime;
#[derive(Insertable, Queryable, Selectable, AsChangeset, Serialize, Deserialize, Identifiable)]
#[diesel(primary_key(puuid))]
#[diesel(table_name = account)]
pub struct Account {
    pub puuid: String,
    pub game_name: String,
    pub tag_line: String,
}

#[derive(Insertable, Queryable, Selectable, AsChangeset, Serialize, Deserialize)]
#[diesel(table_name = match_)]
pub struct Match {
    pub id: String,
    pub start_timestamp: NaiveDateTime,
    pub duration: i64,
    pub queue_id: i64,
    pub game_version: String,
    pub game_mode: String,
    pub winning_team_id: i64,
    pub surrender: bool,
}

#[derive(Insertable, Queryable, Selectable, AsChangeset, Serialize, Deserialize)]
#[diesel(table_name = match_stats)]
pub struct MatchStat {
    pub id: String,
    pub puuid: String,
    pub match_id: String,
    pub kills: i64,
    pub deaths: i64,
    pub assists: i64,
    pub champion_id: i64,
    pub position: String,
    pub longest_time_spent_living: i64,
    pub time_spent_dead: i64,
    pub team_id: i64,
}
