[package]
name = "int-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
# Workspace
the-collector-ipc = { path = "../../lib/the-collector-ipc" }
the-collector-db = { path = "../../lib/the-collector-db" }

# 3P
anyhow = "1.0.95"
async-trait = { version = "0.1.83" }
bincode = "1.3.3"
dotenv = "0.15.0"
nng = "1.0.1"
poise = { version = "0.6.1" }
riven = "2.57.0"
serde = { version = "1.0.217", features = ["derive"] }
tokio = { version = "1.37.0", features = ["full"] }
tracing = { version = "0.1.41" }
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
