[package]
name = "int-bot"
version.workspace = true
edition = "2021"

[dependencies]
# Workspace
the-collector-ipc = { path = "../../lib/the-collector-ipc" }
the-collector-db = { path = "../../lib/the-collector-db" }
the-collector-evaluation = { path = "../../lib/the-collector-evaluation" }

# 3P
anyhow = "1.0.95"
async-trait = { version = "0.1.83" }
dotenvy = "0.15.7"
lazy_static = { version = "1.5.0" }
poise = { version = "0.6.1" }
riven = "2.57.0"
tokio = { version = "1.37.0", features = ["full"] }
tracing = { version = "0.1.41" }
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
rand = "0.8.5"
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0.217", features = ["derive"] }
tokio-stream = "0.1.17"
openssl = { version = "0.10", features = ["vendored"] }
toml = "0.8.19"
chrono = "0.4.39"
indoc = "2.0.5"
