name: Rust CI - Cross Compilation and Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags (e.g., v1.0.0)

jobs:
  release:
    name: Release - ${{ matrix.target }}
    strategy:
      matrix:
        target: [armv7-unknown-linux-gnueabihf]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: build
          target: ${{ matrix.target }}
          args: "--release"
      - name: Make files executable
        run: |
          chmod +x target/${{ matrix.target }}/release/the-collector
          chmod +x target/${{ matrix.target }}/release/int-bot
      - name: Create gzipped tarball
        run: tar -czvf target/${{ matrix.target }}/the-collector.tar.gz \
          target/${{ matrix.target }}/release/the-collector \
          target/${{ matrix.target }}/release/int-bot
      - name: Create release on GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: target/${{ matrix.target }}/the-collector.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
