name: Rust CI - Cross Compilation and Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags (e.g., v1.0.0)

jobs:
  release:
    name: Release - ${{ matrix.target }}
    strategy:
      matrix:
        target: [armv7-unknown-linux-gnueabihf, aarch64-apple-darwin]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: ${{ matrix.command }}
          target: ${{ matrix.target }}
          args: "--release"
          strip: true
      - name: Create release on GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/${{ matrix.target }}/the-collector"
            target/${{ matrix.target }}/release/int-bot
